### ISSUE TITLE
Soft banned

### ISSUE THREAD

**Issue by Baiize** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#11]
I just got soft banned using your product.
https://imgur.com/LMwWhN9

Not picked any items up, not used any cheat programs what so ever. The only difference in my play has been PvP Watchdog which I have used exclusively for around a week. Now I am soft banned. :)

**Comment by knightabe** [comment]
I've just had the same issue. No CE ever, haven't picked up anything from users. Only change is my use of watchdog.

**Comment by knightabe** [comment]
Update, I did more research, and it's not a soft ban, I'm fully banned. I never even got a notice about invalid game data.

**Comment by LukeYui** [comment]
It's a softban, so essentially your online will be restricted to other softbanned players.

Emailing [Bandai Namco support](https://service-en.bandainamcoent.eu/app/detail/a_id/2309/p/6856) (EU link included) to explain the situation and request your softban to be lifted is your best bet at the moment, but this will take time on their end. If you want to play PvP sooner than this, I recommend you use an alternate steam account to family share the game and play this way.

**Comment by DrShibaInu** [comment]
how long do you guess this will take? and doesnt jelly baby play test this you need to make sure whatever you make doesnt BAN you said specifically it wouldnt i got a stream of 200 people to get watchdogs and now they are all including me banned and you kinda have to update because if you dont it often times ds3 will crash over and over. please double check next time good night.

**Comment by Baiize** [comment]
Not good enough really. You made out like it was tested and ban proof, in every iteration of the text prior to recently it stated "This doesn't get you soft banned, and if you've been banned then prove it." Well you got a lot of people banned.

**Comment by LukeYui** [comment]
I'm not downplaying the impact this had, I understand that a lot of people have been banned and I agree that this is absolutely unacceptable.

Watchdog makes numerous memory edits that would otherwise ban, had the anti-cheat not been bypassed. We were confident that it was fully disabled because these other edits were proven to be safe by months and months of testing before release, at the time of posting and the claim was made about the mod being safe we weren't lying, it was the product of 100's of hours of testing with no bans as a result. 

I've mentioned in the previous post the steps that we've taken to ensure this doesn't happen again, but this doesn't change the fact that people have already been banned.

**Comment by DrShibaInu** [comment]
This kind of what i do stream and now i cant do this its annoying i just want to ask how do we know future versions wont have this happen again? And do you have a idea on when we can get our accounts back? Thanks

**Comment by LukeYui** [comment]
Sorry I can't give a time on getting un-banned. In the mean time, seeing as bans work on Steam ID, you can continue playing unrestricted by using an alternate steam account and sharing the game from your main. 

You could play on this alternate account while waiting for your appeal to Bandai Namco to be processed.

For future versions, we're completely reworking our anti-cheat bypass. I think it's apparent that this whole situation has had a massive impact on everyone, ourselves included so we're going to more rigorously test updates before pushing them in the future.

If my word doesn't mean much, which I completely understand, then I recommend waiting for ban waves week by week (which occur on Tuesdays / Wednesdays depending on your time zone) and checking back.

**Comment by DrShibaInu** [comment]
Just to double check for right now i delete watchdogs or use a non ban causjng version and send a email to bandi i dont have to delete saves and resend or anything of the likes?

**Comment by LukeYui** [comment]
Send an email to their support, they'll tell you why you were banned and instruct you further from there. They'll most likely instruct you to delete saves.

**Comment by KamikazeRaven** [comment]
"prove it" huh?

Yeah, here's your proof, I got banned too.
Those who use CE won't get banned, but those who use PVP Watchdog are banned. How ironic.

We all trusted your words.
I am a programmer too. Maybe don't make such bold claims about your programs next time?

Thanks for your works anyway. I'm just really frustrated.

**Comment by DrShibaInu** [comment]
they should have tested the newer updates more for there big promise which is true from now on just wait for that Tuesday wave to see if stuff is true at least they are trying to help im sure they know to be extra careful making a second steam account and putting no money on it and steam sharing you can still play ds3 no problem at all and since darksouls 3 has a password there is no problem getting in contact with friends for transfers to wait out for the other accounts there just isn't anything else you can do if you dont have anyone to transfer ill try to help any one else out that needs it for items or area progression discord name is Dark soul boi#5140 if you want help or anything

**Comment by Baiize** [comment]
You'll be forced to delete your entire save file on DS3, create a new character once that's donw and play it for about 30 minutes or so, then wait a month (minimum) to have your soft ban lifted. That's what FromSoft support told me in 2 separate conversations.
You can like mentioned above use family share, but personally I'm just taking a vacation from DS for the month and seeing if it pans out, I won't be using or encouraging use of this product again either.
I really do appreciate the time and effort you guys put in and the idea behind it, I think it's admirable but I just can't put my faith back into this given what has happened.

I wish you the best of luck with future updates and I really do hope it goes well for those who continue to use the program.

**Comment by Jellybaby34** [comment]
Fixed in the more recent builds so I'm closing this issue. Builds are more rigorously tested as a result of this.
