### ISSUE TITLE
So watchdogs is good to have but inperfect as it seems.

### ISSUE THREAD

**Issue by Oneamongmanyothers** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#17]
The anti-crash and anti-curse part of watchdogs seems to be working perfectly, that said however its detection seems abit flawed. I have a friend who hacks this game frequently and he was able to summon into both my world and one of my other friends with us both having watchdogs. He was able to change from white to red or any of the other status, no clip, enable a speedhack and infinite health. All of this while BOTH of us had it set to auto-kick. Honestly for as good as this is the biggest drawback I see to it is not putting the kick function in the hands of the player using it. I had a match earlier in the undead arena where some fuckboi tried to crash my game 3 times after it failed 3 times, he wised up and decided to chuck me into the side of a mountain. If I had the ability to kick or even just leave other sessions at will it would have solved the entire issue. I am aware this could potentially be abused but I don't see how this would mess with invasions any more then simply pulling your Ethernet cord out. Hackers are usually fairly smart people, can't fool a human though,

**Comment by LukeYui** [comment]
Hello, thanks for your feedback.

1) Regarding the cheats that weren't detected that you mentioned, I'm afraid these are extremely hard to detect. There have been some methods developed to detect them but they've all been scrapped due to the possibility of causing false positives, but it's still being looked into further.

2) Once the anti-cheat bypass has been re-worked and thoroughly tested, there are over 20 new patches ready to be added to the next version of watchdog. These should address even the rarest and most malicious of cheats.

3) I understand what you said about wanting to allow kicking other players freely, but I feel this would damage the online of Dark Souls III as, in theory, people can and will just kick people they think have annoying builds or don't want to play against. They can still do this by Alt+F4ing or disconnecting from the internet but this is much more inconvenient for them, and much harder than just removing someone from their session.

4) There are actually only very few cheaters that I've seen who know what they're doing, the vast majority just use public scripts to do their bidding. As mentioned before, the next version should address most if not all public cheats and in addition to this make cheaters much less intrusive (they'll just disappear as opposed to causing any trouble).

I recommend just blocking any cheaters that you encounter once, so they don't feel like they have anything to prove once they fail the first time. Again, the next version of watchdog will make it much easier to identify, block and cross reference cheater profiles, so this should be improved next time.
