### ISSUE TITLE
Estus and Ashen estus not refilling after killing invader

### ISSUE THREAD

**Issue by spiffy0ne** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#21]
I was summoned into a friends world and after killing numerous invaders my estus or ashen estus never refilled.  I uninstalled (deleted file) and my estus went back to refilling again.

**Comment by outryder** [comment]
Thanks for the work, guys. I have used Watchdog 1.0.5 for since June. It really helped heavily mitigate cheater issues in DS3. First 2-3 months after release it helped in 90-95% cheater cases (maybe closer to 99% :-) ). 
Later it got crashed (August, September) by cheaters several times (rare cases) after their appearance in another host's world (during my invasions); some invaders (cheaters) couldn't be kicked out during my host session (rare cases, in September) - they stayed in invisible state; also Steam updates (when auto-downloaded and ready to install) seem to crash the Watchdog "app" (1.0.5) - crashes occurred on days with updates and notifications for Steam required to restart to apply updates.
I tried the 1.0.6 version today and no estus (any kind) was refilled after killing any phantoms. So far, it is the only issue with this version.

**Comment by spiffy0ne** [comment]
So i'm tired of using 1.05 because of this issue so I tried 1.06 again and tried uninstalling Wex Dust mod to see if that was the problem and nothing changes.  My estus will not refill when I'm hosting and killing invaders or if I'm summoned and killing invaders.  I opened this up a month ago and you haven't commented on it or acknowledged the issue yet I see you commenting on everyone elses problems.

Can you give me some assistance an idea anything?  I really like having the username next to the playername and I don't have this feature in 1.05.  Plus 1.05 crashes constantly from that polygon issue.  Please a little assistance.  Thank you for your time.

**Comment by LukeYui** [comment]
Hello, apologies for not replying to this thread; I have been looking into this because a related bug was reported on the Nexus Mods page.

I've looked into it, used the mod myself etc. and am struggling to re-create the bug:
Is it only when you're killing invaders, what if you're an invader yourself killing phantoms?

**Comment by spiffy0ne** [comment]
Thank you for replying Luke,
Ok I did some further testing for you on 1.06 and when I invaded and won it always hangs after hosts death and then gives me connection error, EVERY time.  Also I received no estus refills after a phantom was killed.

My settings are as follow : Boot screen disabled,text size 16,version display disabled and everything else is default.  I tried altering text size back to default but that changed nothing.  When I use 1.05 everything works perfectly except for polygon error crash occasionally.  

Any other info you need please let me know.

**Comment by outryder** [comment]
When I deleted the version 1.0.5 left-overs and copied 1.0.6 contents into DS3 game folder, I started to get **connection error** _every time host is defeated_, which I didn't have initially (at first 1.0.6 try-out). 
Still don't get the estus refill (any kind), when kill a (white/blue) phantom (as invader) or any other phantom is killed by any other player (white/blue/red/purple/farron).
P.S. I didn't ever use any mods or etc on DS3.

**Comment by LukeYui** [comment]
That's strange, seeing as I can't manage to get the bug to occur for me, I'll disable that particular bit of code in the next patch, it'll be out soon.

**Comment by outryder** [comment]
Thank you, LukeYui!
I hope that fixes the issues! I will post the results here when I install and try it out.

**Comment by outryder** [comment]
I had suspicion there isn't such a bug in Win10. So a clean install (with all exact same programs and components) proved no bug after all. (must be only for Windows 7)

**Comment by spiffy0ne** [comment]
You beautiful bastard. Yoy fixed the Win7 issue with Estus not refiling..Thank youso much and keep up the good work!!
