### ISSUE TITLE
What's the latest version? 

### ISSUE THREAD

**Issue by UkrainianCitizen** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#41]
There is an error on Nexus - last version is 1.0.7 clearly , coming from commits and chengelog, but the archive on Nexus has a version 1.0.8.
But d3d11.dll and VERSION file contain 1.0.8 number. What are these inconsistencies? What's the latest version?

**Comment by outryder** [comment]
LukeYui, hi!

Just to make clear for others:
GitHub 1.0.7 beta = Nexus 1.0.7 (22 March 2020)
GitHub 1.0.7         = Nexus 1.0.8 (29 March 2020)
?

Because that's what it looks like to me.

**Comment by LukeYui** [comment]
I'm confused, the version should be in the VERSION file in this Git repo. They should both be 1.0.8

**Comment by outryder** [comment]
As I haven't played DS3 for a while, I didn't update the Watchdog on my PC.

Also a question, if 1.0.8 is a current version, and 1.0.7 and 1.0.8 are somehow different: what has changed for 1.0.8? Because GitHub shows changelog text for 1.0.7 only: 
https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/blob/master/CHANGELOG.txt

**Comment by LukeYui** [comment]
The versions seem a bit confusing at the moment, we'll work on making it easier to tell what is what. The latest versions will always be here though, and the NexusMods page.
