### ISSUE TITLE
Does not detect players in god mode

### ISSUE THREAD

**Issue by AntonioCS** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#58]
Hey,

Today I was playing someone that I could not hit. It wasn't because they were better than me and that I suck at the game, it was simply because I believe collisions were disabled or something along those lines.
Watchdog did not report anything. The user displayed as a normal user.
Anyway watchdog can detect these things?

**Comment by Ronolus** [comment]
Same thing. Host and phantoms can take no damage from top lightning spell + top chime, and they are not reported as cheating

**Comment by LukeYui** [comment]
Watchdog cannot detect these things, because it is not sent over the network. I've tried and tried to build functions that can flag infinite iframe/no dead users, but they all have a similar 2 - 5% false positive rate which is unacceptable.

Watchdog is still being worked on though, and if there are any breakthroughs I'll let you know.

**Comment by AntonioCS** [comment]
Shame :(
