### ISSUE TITLE
strange report of unreal level

### ISSUE THREAD

**Issue by Ronolus** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#59]
2 times today I saw hosts reported having illegal level (1 lower than real, srlsy?) and then they became green when got phantoms (but phantoms were still reported as having illegal level, still -1 to real)
I mean definetely noone wants to lower his/her level only by 1, so it might be your calculator issue.

**Comment by LukeYui** [comment]
Some popular mule accounts/saves are off by 1 soul level, watchdog's SL calculation is exact because there is a simple formula for caluclating someone's "actual" soul level. I've come across 100's of accounts over the last year either 1 level below or 1 level above their actual soul level.

If watchdog's calculations were incorrect, it would be an absolute disaster, and every legit person would be flagged.

**Comment by outryder** [comment]
^ more or less common.
Also seen some "builds" with 0 Int, 0 Fth, 0 Luck. LOL
